<?
    $this->inlineScript()
        ->appendFile($this->basePath('js/controller/index/listar.js'));

?>

<div class="row" ng-app="AppAngular" ng-controller="listarQuizController">
    <div class="col-md-12 text-center">
        Chose a quiz
    </div>
    <div class="col-md-12">
            <div class="alert alert-info text-center">
                Quiz
            </div>
            <div class="alert alert-info text-center">
                Quiz
            </div>
    </div>

</div>