-- MySQL Script generated by MySQL Workbench
-- ter 31 jul 2018 16:53:07 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema QUIZ_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema QUIZ_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `QUIZ_DB` ;
USE `QUIZ_DB` ;

-- -----------------------------------------------------
-- Table `QUIZ_DB`.`admin_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QUIZ_DB`.`admin_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `create_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QUIZ_DB`.`quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QUIZ_DB`.`quiz` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `create_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QUIZ_DB`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QUIZ_DB`.`type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QUIZ_DB`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QUIZ_DB`.`question` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quiz_id` INT UNSIGNED NOT NULL,
  `type_id` INT UNSIGNED NOT NULL,
  `subject` VARCHAR(45) NOT NULL,
  `create_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `quiz_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_qst_qiz_idx` (`quiz_id` ASC),
  INDEX `fk_qst_typ_idx` (`type_id` ASC),
  CONSTRAINT `fk_qst_qiz`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `QUIZ_DB`.`quiz` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_qst_typ`
    FOREIGN KEY (`type_id`)
    REFERENCES `QUIZ_DB`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QUIZ_DB`.`option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QUIZ_DB`.`option` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `question_id` INT UNSIGNED NOT NULL,
  `answer` VARCHAR(100) NOT NULL,
  `is_correct` TINYINT NOT NULL,
  `create_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `question_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `answer_UNIQUE` (`answer` ASC),
  INDEX `fk_ptn_qst_idx` (`question_id` ASC),
  CONSTRAINT `fk_ptn_qst`
    FOREIGN KEY (`question_id`)
    REFERENCES `QUIZ_DB`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QUIZ_DB`.`participant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QUIZ_DB`.`participant` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `create_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QUIZ_DB`.`result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QUIZ_DB`.`result` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `participant_id` INT UNSIGNED NOT NULL,
  `quiz_id` INT UNSIGNED NOT NULL,
  `started_at` DATETIME NOT NULL,
  `finished_at` DATETIME NULL,
  PRIMARY KEY (`id`, `participant_id`, `quiz_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_rlt_prt_idx` (`participant_id` ASC),
  INDEX `fk_rlt_qiz_idx` (`quiz_id` ASC),
  CONSTRAINT `fk_rlt_prt`
    FOREIGN KEY (`participant_id`)
    REFERENCES `QUIZ_DB`.`participant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rlt_qiz`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `QUIZ_DB`.`quiz` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QUIZ_DB`.`answered`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QUIZ_DB`.`answered` (
  `result_id` INT UNSIGNED NOT NULL,
  `option_id` INT UNSIGNED NOT NULL,
  `question_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`result_id`, `option_id`, `question_id`),
  INDEX `fk_nsw_rlt_idx` (`result_id` ASC),
  INDEX `fk_nsw_ptn_idx` (`option_id` ASC),
  INDEX `fk_nsw_qst_idx` (`question_id` ASC),
  CONSTRAINT `fk_nsw_rlt`
    FOREIGN KEY (`result_id`)
    REFERENCES `QUIZ_DB`.`result` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nsw_ptn`
    FOREIGN KEY (`option_id`)
    REFERENCES `QUIZ_DB`.`option` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nsw_qst`
    FOREIGN KEY (`question_id`)
    REFERENCES `QUIZ_DB`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
