<?php
/**
 *
 * @category   Trezo
 * @package    Trezo_Payments
 * @author     Rone Clay Santos <https://github.com/roneclay>
 */
?>
<?php $boleto_url = Mage::helper('trezo_payments')->getOrderBoletoUrl( $this->getInfo()->getData('parent_id') ) ?>
<?php echo $this->htmlEscape($this->getMethod()->getTitle()) .' ' ?>
<?php if($boleto_url): ?>
    - <a href="<?php echo $boleto_url ?>" target="_blank"><?php echo $this->__('Print Boleto') ?></a>
<?php endif ?>
