<h1>Input Purchase Info to generate Quotation</h1>
<form action="<?php echo $this->getFormAction() ?>" method="post">
    <h3>Seller CEP</h3><input name="sellercep" type="text" value="13015300"/>
    <h3>Recipient CEP</h3><input name="recipientcep" type="text" value="04011060"/>
    <h3>Recipíent Country</h3><input name="recipientcountry" type="text" value="BR"/>
    <h3>Shipment Invoice Value</h3><input name="shipmentinvoicevalue" type="text" value="100.87"/>
    <h3>Weight</h3><input name="weight" type="text" value="2.1"/>
    <h3>Length</h3><input name="length" type="text" value="14"/>
    <h3>Height</h3><input name="height" type="text" value="20"/>
    <h3>Width</h3><input name="width" type="text" value="15"/>
    <h3>Quantity</h3><input name="quantity" type="text" value="1"/>
    <input name="submit" type="submit" value="Submit">
</form>