<?php

namespace Application\Entidade;

/**
 * ParticipantAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
