<?php

namespace Application\Entidade;

/**
 * QuestionOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
